import typography from "@tailwindcss/typography";
import { type Config } from "tailwindcss";
import tailwindAnimate from "tailwindcss-animate";

export default {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		"./registry/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					"var(--font-inter), sans-serif",
					{
						fontVariationSettings: "opsz 32",
					},
				],
			},
			colors: {
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				outline: {
					white: "var(--ef-outline-white, #fff)",
					"gray-1": "var(--ef-outline-gray-1, #ededed)",
					"gray-2": "var(--ef-outline-gray-2, #e2e2e2)",
					"gray-3": "var(--ef-outline-gray-3, #c7c7c7)",
					"gray-4": "var(--ef-outline-gray-4, #999)",
					"gray-5": "var(--ef-outline-gray-5, #383838)",
					"red-2": "var(--ef-outline-red-2, #fdc2c2)",
					"red-3": "var(--ef-outline-red-3, #f79596)",
					"red-4": "var(--ef-outline-red-4, #e03636)",
					"green-2": "var(--ef-outline-green-2, #a6efc0)",
					"green-3": "var(--ef-outline-green-3, #86e0a8)",
					"amber-2": "var(--ef-outline-amber-2, #fbdb73)",
					"amber-3": "var(--ef-outline-amber-3, #fbcc55)",
					"blue-2": "var(--ef-outline-blue-2, #a7d7fd)",
					"orange-3": "var(--ef-outline-orange-3, #f4b07f)",
					"violet-2": "var(--ef-outline-violet-2, #c9bafb)",
					"gray-modals": "var(--ef-outline-gray-modals, #ededed)",
				},
				ink: {
					white: "var(--ef-ink-white, #fff)",
					"gray-1": "var(--ef-ink-gray-1, #ededed)",
					"gray-2": "var(--ef-ink-gray-2, #e2e2e2)",
					"gray-3": "var(--ef-ink-gray-3, #c7c7c7)",
					"gray-4": "var(--ef-ink-gray-4, #999)",
					"gray-5": "var(--ef-ink-gray-5, #7c7c7c)",
					"gray-6": "var(--ef-ink-gray-6, #525252)",
					"gray-7": "var(--ef-ink-gray-7, #383838)",
					"gray-8": "var(--ef-ink-gray-8, #171717)",
					"red-1": "var(--ef-ink-red-1, #fff7f7)",
					"red-2": "var(--ef-ink-red-2, #f79596)",
					"red-3": "var(--ef-ink-red-3, #e03636)",
					"red-4": "var(--ef-ink-red-4, #cc2929)",
					"green-1": "var(--ef-ink-green-1, #f2fdf4)",
					"green-3": "var(--ef-ink-green-3, #46b37e)",
					"green-4": "var(--ef-ink-green-4, #278f5e)",
					"amber-1": "var(--ef-ink-amber-1, #fdfaed)",
					"amber-3": "var(--ef-ink-amber-3, #e79913)",
					"amber-4": "var(--ef-ink-amber-4, #db7706)",
					"blue-1": "var(--ef-ink-blue-1, #f2f9ff)",
					"blue-3": "var(--ef-ink-blue-3, #0289f7)",
					"blue-4": "var(--ef-ink-blue-4, #007be0)",
					"cyan-3": "var(--ef-ink-cyan-3, #3bbde5)",
					"violet-1": "var(--ef-ink-violet-1, #fbfaff)",
					"violet-3": "var(--ef-ink-violet-3, #6846e3)",
					"blue-link": "var(--ef-ink-blue-link, #73bbf6)",
				},
				surface: {
					white: "var(--ef-surface-white, #fff)",
					"gray-1": "var(--ef-surface-gray-1, #f8f8f8)",
					"gray-2": "var(--ef-surface-gray-2, #f3f3f3)",
					"gray-3": "var(--ef-surface-gray-3, #ededed)",
					"gray-4": "var(--ef-surface-gray-4, #e2e2e2)",
					"gray-5": "var(--ef-surface-gray-5, #525252)",
					"gray-6": "var(--ef-surface-gray-6, #383838)",
					"gray-7": "var(--ef-surface-gray-7, #171717)",
					"red-1": "var(--ef-surface-red-1, #fff7f7)",
					"red-2": "var(--ef-surface-red-2, #ffe7e7)",
					"red-3": "var(--ef-surface-red-3, #ffd8d8)",
					"red-4": "var(--ef-surface-red-4, #fdc2c2)",
					"red-5": "var(--ef-surface-red-5, #cc2929)",
					"red-6": "var(--ef-surface-red-6, #b52a2a)",
					"red-7": "var(--ef-surface-red-7, #941f1f)",
					"green-1": "var(--ef-surface-green-1, #f2fdf4)",
					"green-2": "var(--ef-surface-green-2, #e4faeb)",
					"green-5": "var(--ef-surface-green-5, #278f5e)",
					"amber-1": "var(--ef-surface-amber-1, #fdfaed)",
					"amber-2": "var(--ef-surface-amber-2, #fff7d3)",
					"amber-5": "var(--ef-surface-amber-5, #db7706)",
					"blue-1": "var(--ef-surface-blue-1, #f2f9ff)",
					"blue-2": "var(--ef-surface-blue-2, #e6f4ff)",
					"blue-5": "var(--ef-surface-blue-5, #007be0)",
					"orange-2": "var(--ef-surface-orange-2, #ffefe4)",
					"violet-2": "var(--ef-surface-violet-2, #eee8ff)",
					"violet-5": "var(--ef-surface-violet-5, #5a3eba)",
					"cyan-2": "var(--ef-surface-cyan-2, #ddf7ff)",
					"menu-bar": "var(--ef-surface-menu-bar, #f8f8f8)",
					cards: "var(--ef-surface-cards, #fff)",
					modal: "var(--ef-surface-modal, #fff)",
					selected: "var(--ef-surface-selected, #fff)",
				},
				focus: {
					light: {
						default: "var(--ef-focus-light-default, #c9c9c9)",
					},
				},
			},
			fontSize: {
				"ef-tiny": "var(--ef-font-size-tiny, 11px)",
				"ef-2xs": "var(--ef-font-size-2xs, 11px)",
				"ef-xs": "var(--ef-font-size-xs, 12px)",
				"ef-sm": "var(--ef-font-size-sm, 13px)",
				"ef-base": "var(--ef-font-size-base, 14px)",
				"ef-lg": "var(--ef-font-size-lg, 16px)",
				"ef-xl": "var(--ef-font-size-xl, 18px)",
				"ef-2xl": "var(--ef-font-size-2xl, 20px)",
				"ef-3xl": "var(--ef-font-size-3xl, 24px)",
				"ef-4xl": "var(--ef-font-size-4xl, 26px)",
				"ef-5xl": "var(--ef-font-size-5xl, 28px)",
				"ef-6xl": "var(--ef-font-size-6xl, 32px)",
				"ef-7xl": "var(--ef-font-size-7xl, 40px)",
				"ef-8xl": "var(--ef-font-size-8xl, 44px)",
				"ef-9xl": "var(--ef-font-size-9xl, 48px)",
				"ef-10xl": "var(--ef-font-size-10xl, 52px)",
				"ef-11xl": "var(--ef-font-size-11xl, 56px)",
				"ef-12xl": "var(--ef-font-size-12xl, 64px)",
				"ef-13xl": "var(--ef-font-size-13xl, 72px)",
				"ef-14xl": "var(--ef-font-size-14xl, 80px)",
				"ef-15xl": "var(--ef-font-size-15xl, 88px)",
			},
			lineHeight: {
				"ef-tiny": "var(--ef-line-height-tiny)",
				"ef-2xs": "var(--ef-line-height-2xs)",
				"ef-xs": "var(--ef-line-height-xs)",
				"ef-sm": "var(--ef-line-height-sm)",
				"ef-base": "var(--ef-line-height-base)",
				"ef-lg": "var(--ef-line-height-lg)",
				"ef-xl": "var(--ef-line-height-xl)",
				"ef-2xl": "var(--ef-line-height-2xl)",
				"ef-3xl": "var(--ef-line-height-3xl)",
				"ef-4xl": "var(--ef-line-height-4xl)",
				"ef-5xl": "var(--ef-line-height-5xl)",
				"ef-6xl": "var(--ef-line-height-6xl)",
				"ef-7xl": "var(--ef-line-height-7xl)",
				"ef-8xl": "var(--ef-line-height-8xl)",
				"ef-9xl": "var(--ef-line-height-9xl)",
				"ef-10xl": "var(--ef-line-height-10xl)",
				"ef-11xl": "var(--ef-line-height-11xl)",
				"ef-12xl": "var(--ef-line-height-12xl)",
				"ef-13xl": "var(--ef-line-height-13xl)",
				"ef-14xl": "var(--ef-line-height-14xl)",
				"ef-15xl": "var(--ef-line-height-15xl)",
			},
			fontWeight: {
				"ef-regular": "var(--ef-font-weight-regular)",
				"ef-medium": "var(--ef-font-weight-medium)",
				"ef-semibold": "var(--ef-font-weight-semibold)",
				"ef-bold": "var(--ef-font-weight-bold)",
				"ef-black": "var(--ef-font-weight-black)",
			},
			borderRadius: {
				"ef-0": "var(--ef-radius-0, 0px)",
				"ef-1": "var(--ef-radius-1, 4px)",
				"ef-2": "var(--ef-radius-2, 5px)",
				"ef-3": "var(--ef-radius-3, 6px)",
				"ef-4": "var(--ef-radius-4, 8px)",
				"ef-5": "var(--ef-radius-5, 10px)",
				"ef-6": "var(--ef-radius-6, 12px)",
				"ef-7": "var(--ef-radius-7, 16px)",
				"ef-8": "var(--ef-radius-8, 20px)",
				"ef-9": "var(--ef-radius-9, 9999px)",
			},
			spacing: {
				"ef-0": "var(--ef-spacing-0, 0px)",
				"ef-1": "var(--ef-spacing-1, 1px)",
				"ef-2": "var(--ef-spacing-2, 2px)",
				"ef-3": "var(--ef-spacing-3, 3px)",
				"ef-4": "var(--ef-spacing-4, 4px)",
				"ef-5": "var(--ef-spacing-5, 5px)",
				"ef-6": "var(--ef-spacing-6, 6px)",
				"ef-7": "var(--ef-spacing-7, 7px)",
				"ef-8": "var(--ef-spacing-8, 8px)",
				"ef-9": "var(--ef-spacing-9, 9px)",
				"ef-10": "var(--ef-spacing-10, 10px)",
				"ef-11": "var(--ef-spacing-11, 11px)",
				"ef-12": "var(--ef-spacing-12, 12px)",
				"ef-13": "var(--ef-spacing-13, 14px)",
				"ef-14": "var(--ef-spacing-14, 16px)",
				"ef-15": "var(--ef-spacing-15, 20px)",
				"ef-16": "var(--ef-spacing-16, 26px)",
			},
			boxShadow: {
				"ef-xl":
					"0px 0px 1px 0px rgba(0, 0, 0, 0.20), 0px 0px 10px 2px rgba(0, 0, 0, 0.04), 0px 24px 30px -8px rgba(0, 0, 0, 0.10)",
			},
		},
	},
	plugins: [tailwindAnimate, typography],
} satisfies Config;
