import typography from "@tailwindcss/typography";
import { type Config } from "tailwindcss";
import tailwindAnimate from "tailwindcss-animate";
import defaultTheme from "tailwindcss/defaultTheme";

export default {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		"./registry/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					`var(--font-inter), ${defaultTheme.fontFamily.sans.join(", ")}`,
					{ fontVariationSettings: '"opsz" 32' },
				],
			},
			colors: {
				outline: {
					white: "var(--ef-outline-white)",
					"gray-1": "var(--ef-outline-gray-1)",
					"gray-2": "var(--ef-outline-gray-2)",
					"gray-3": "var(--ef-outline-gray-3)",
					"gray-4": "var(--ef-outline-gray-4)",
					"gray-5": "var(--ef-outline-gray-5)",
					"red-2": "var(--ef-outline-red-2)",
					"red-3": "var(--ef-outline-red-3)",
					"red-4": "var(--ef-outline-red-4)",
					"green-2": "var(--ef-outline-green-2)",
					"green-3": "var(--ef-outline-green-3)",
					"amber-2": "var(--ef-outline-amber-2)",
					"amber-3": "var(--ef-outline-amber-3)",
					"blue-2": "var(--ef-outline-blue-2)",
					"orange-3": "var(--ef-outline-orange-3)",
					"violet-2": "var(--ef-outline-violet-2)",
					"gray-modals": "var(--ef-outline-gray-modals)",
				},
				ink: {
					white: "var(--ef-ink-white)",
					"gray-1": "var(--ef-ink-gray-1)",
					"gray-2": "var(--ef-ink-gray-2)",
					"gray-3": "var(--ef-ink-gray-3)",
					"gray-4": "var(--ef-ink-gray-4)",
					"gray-5": "var(--ef-ink-gray-5)",
					"gray-6": "var(--ef-ink-gray-6)",
					"gray-7": "var(--ef-ink-gray-7)",
					"gray-8": "var(--ef-ink-gray-8)",
					"red-1": "var(--ef-ink-red-1)",
					"red-2": "var(--ef-ink-red-2)",
					"red-3": "var(--ef-ink-red-3)",
					"red-4": "var(--ef-ink-red-4)",
					"green-1": "var(--ef-ink-green-1)",
					"green-3": "var(--ef-ink-green-3)",
					"green-4": "var(--ef-ink-green-4)",
					"amber-1": "var(--ef-ink-amber-1)",
					"amber-3": "var(--ef-ink-amber-3)",
					"amber-4": "var(--ef-ink-amber-4)",
					"blue-1": "var(--ef-ink-blue-1)",
					"blue-3": "var(--ef-ink-blue-3)",
					"blue-4": "var(--ef-ink-blue-4)",
					"cyan-3": "var(--ef-ink-cyan-3)",
					"violet-1": "var(--ef-ink-violet-1)",
					"violet-3": "var(--ef-ink-violet-3)",
					"blue-link": "var(--ef-ink-blue-link)",
				},
				surface: {
					white: "var(--ef-surface-white)",
					"gray-1": "var(--ef-surface-gray-1)",
					"gray-2": "var(--ef-surface-gray-2)",
					"gray-3": "var(--ef-surface-gray-3)",
					"gray-4": "var(--ef-surface-gray-4)",
					"gray-5": "var(--ef-surface-gray-5)",
					"gray-6": "var(--ef-surface-gray-6)",
					"gray-7": "var(--ef-surface-gray-7)",
					"red-1": "var(--ef-surface-red-1)",
					"red-2": "var(--ef-surface-red-2)",
					"red-3": "var(--ef-surface-red-3)",
					"red-4": "var(--ef-surface-red-4)",
					"red-5": "var(--ef-surface-red-5)",
					"red-6": "var(--ef-surface-red-6)",
					"red-7": "var(--ef-surface-red-7)",
					"green-1": "var(--ef-surface-green-1)",
					"green-2": "var(--ef-surface-green-2)",
					"green-5": "var(--ef-surface-green-5)",
					"amber-1": "var(--ef-surface-amber-1)",
					"amber-2": "var(--ef-surface-amber-2)",
					"amber-5": "var(--ef-surface-amber-5)",
					"blue-1": "var(--ef-surface-blue-1)",
					"blue-2": "var(--ef-surface-blue-2)",
					"blue-5": "var(--ef-surface-blue-5)",
					"orange-2": "var(--ef-surface-orange-2)",
					"violet-2": "var(--ef-surface-violet-2)",
					"violet-5": "var(--ef-surface-violet-5)",
					"cyan-2": "var(--ef-surface-cyan-2)",
					"menu-bar": "var(--ef-surface-menu-bar)",
					cards: "var(--ef-surface-cards)",
					modal: "var(--ef-surface-modal)",
					selected: "var(--ef-surface-selected)",
				},
				focus: {
					light: {
						default: "var(--ef-focus-light-default)",
					},
				},
			},
			fontSize: {
				"ef-tiny": "var(--ef-font-size-tiny)",
				"ef-2xs": "var(--ef-font-size-2xs)",
				"ef-xs": "var(--ef-font-size-xs)",
				"ef-sm": "var(--ef-font-size-sm)",
				"ef-base": "var(--ef-font-size-base)",
				"ef-lg": "var(--ef-font-size-lg)",
				"ef-xl": "var(--ef-font-size-xl)",
				"ef-2xl": "var(--ef-font-size-2xl)",
				"ef-3xl": "var(--ef-font-size-3xl)",
				"ef-4xl": "var(--ef-font-size-4xl)",
				"ef-5xl": "var(--ef-font-size-5xl)",
				"ef-6xl": "var(--ef-font-size-6xl)",
				"ef-7xl": "var(--ef-font-size-7xl)",
				"ef-8xl": "var(--ef-font-size-8xl)",
				"ef-9xl": "var(--ef-font-size-9xl)",
				"ef-10xl": "var(--ef-font-size-10xl)",
				"ef-11xl": "var(--ef-font-size-11xl)",
				"ef-12xl": "var(--ef-font-size-12xl)",
				"ef-13xl": "var(--ef-font-size-13xl)",
				"ef-14xl": "var(--ef-font-size-14xl)",
				"ef-15xl": "var(--ef-font-size-15xl)",
			},
			lineHeight: {
				"ef-tiny": "var(--ef-line-height-tiny)",
				"ef-2xs": "var(--ef-line-height-2xs)",
				"ef-xs": "var(--ef-line-height-xs)",
				"ef-sm": "var(--ef-line-height-sm)",
				"ef-base": "var(--ef-line-height-base)",
				"ef-lg": "var(--ef-line-height-lg)",
				"ef-xl": "var(--ef-line-height-xl)",
				"ef-2xl": "var(--ef-line-height-2xl)",
				"ef-3xl": "var(--ef-line-height-3xl)",
				"ef-4xl": "var(--ef-line-height-4xl)",
				"ef-5xl": "var(--ef-line-height-5xl)",
				"ef-6xl": "var(--ef-line-height-6xl)",
				"ef-7xl": "var(--ef-line-height-7xl)",
				"ef-8xl": "var(--ef-line-height-8xl)",
				"ef-9xl": "var(--ef-line-height-9xl)",
				"ef-10xl": "var(--ef-line-height-10xl)",
				"ef-11xl": "var(--ef-line-height-11xl)",
				"ef-12xl": "var(--ef-line-height-12xl)",
				"ef-13xl": "var(--ef-line-height-13xl)",
				"ef-14xl": "var(--ef-line-height-14xl)",
				"ef-15xl": "var(--ef-line-height-15xl)",
			},
			fontWeight: {
				"ef-regular": "var(--ef-font-weight-regular)",
				"ef-medium": "var(--ef-font-weight-medium)",
				"ef-semibold": "var(--ef-font-weight-semibold)",
				"ef-bold": "var(--ef-font-weight-bold)",
				"ef-black": "var(--ef-font-weight-black)",
			},
			borderRadius: {
				"ef-0": "var(--ef-radius-0)",
				"ef-1": "var(--ef-radius-1)",
				"ef-2": "var(--ef-radius-2)",
				"ef-3": "var(--ef-radius-3)",
				"ef-4": "var(--ef-radius-4)",
				"ef-5": "var(--ef-radius-5)",
				"ef-6": "var(--ef-radius-6)",
				"ef-7": "var(--ef-radius-7)",
				"ef-8": "var(--ef-radius-8)",
				"ef-9": "var(--ef-radius-9)",
			},
			spacing: {
				"ef-0": "var(--ef-spacing-0)",
				"ef-1": "var(--ef-spacing-1)",
				"ef-2": "var(--ef-spacing-2)",
				"ef-3": "var(--ef-spacing-3)",
				"ef-4": "var(--ef-spacing-4)",
				"ef-5": "var(--ef-spacing-5)",
				"ef-6": "var(--ef-spacing-6)",
				"ef-7": "var(--ef-spacing-7)",
				"ef-8": "var(--ef-spacing-8)",
				"ef-9": "var(--ef-spacing-9)",
				"ef-10": "var(--ef-spacing-10)",
				"ef-11": "var(--ef-spacing-11)",
				"ef-12": "var(--ef-spacing-12)",
				"ef-13": "var(--ef-spacing-13)",
				"ef-14": "var(--ef-spacing-14)",
				"ef-15": "var(--ef-spacing-15)",
				"ef-16": "var(--ef-spacing-16)",
			},
		},
	},
	plugins: [tailwindAnimate, typography],
} satisfies Config;
