jobs:
  ci:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: 🔬 Linter
        run: pnpm turbo lint:prettier lint:eslint lint:types lint:md lint:package-json lint:spelling
    timeout-minutes: 15
name: CI
on:
  pull_request: ~
  push:
    branches:
      - main
